class CantInsertCurrency(Exception):
    ...

class CurrencyAlreadyExists(Exception):
    ...

class CantGetCurrency(Exception):
    ...

class CantInsertExchangeRate(Exception):
    ...

class ExchangeRateAlreadyExists(Exception):
    ...

class CantGetExchangeRate(Exception):
    ...

class CantUpdateExchangeRate(Exception):
    ...

class IncorrectInput(Exception):
    ...