from typing import Protocol

from currency_exchange.model.models import Currency, ExchangeRate


class CurrencyRepository(Protocol):

    def add(self, currency: Currency) -> Currency: ...

    def get(self, code: str) -> Currency: ...

    def get_all(self) -> list[Currency]: ...

class ExchangeRateRepository(Protocol):

    def add(self, exchange_rate: ExchangeRate) -> ExchangeRate: ...

    def update(self, exchange_rate: ExchangeRate) -> ExchangeRate: ...

    def get(self, base_currency_code: str, target_currency_code: str) -> ExchangeRate: ...

    def get_all(self) -> list[ExchangeRate]: ...